Adds abilities to session token
fumeapp/humble pull request #2
Opened 2022-06-29 22:03 UTC by tcampbPPU

A use case I have is users need to apply certain rules/abilities to session tokens, for example one might create new sessions token for some GitHub integrations/actions which needs the ability to both read & write, while the other token might just need to read. Typically I think most of this logic could be handle by setting some policy depending on the session source, but I need the option to be a bit more granular where it can be customized on any rules that might need to apply for a specific session.

I also wanted to make this look and feel in terms of functionality similar to [Laravel Sanctum](https://laravel.com/docs/9.x/sanctum#introduction)

So I added a `abilities` column to the `sessions` table where this will act as an array of abilities for the session i.e `["read","write"]`, when the value is set to the default `["*"]` we can assume this session have full access, or all abilities.

There are now a few ways to check the session token has the correct access:

You could do the following using the Auth/User instance
   1. `auth()->user()->tokenCan('write')`
   2. `auth()->session()->can('write')`
   3. `$user()->tokenCan('write')`
   4. `$request->user()->tokenCan('write')`

Or apply a middleware similar to Laravel Sanctum

```php
// only pass middleware if the session token has the ["admin"] ability
Route::get('admin', function () {
    return response()->json([
        'success' => true
    ]);
})->middleware(['auth:api', 'ability:admin']);
```

To get the middlewares to work you need to add the following to the `$routeMiddleware` inside of `app/Http/Kernel.php`
```php
// ...
'abilities' => \acidjazz\Humble\Http\Middleware\CheckAbilities::class,
'ability' => \acidjazz\Humble\Http\Middleware\CheckForAnyAbility::class,
// ...
```

I also added a new method where you can easily create new session for the given auth or user instance
```php
 auth()->user()->createToken('action', ['write'])
```

2022-06-29 22:58 UTC, acidjazz requested changes

2022-06-29 22:58 UTC, acidjazz commented on migrations/create_humble_tables.php
> +            $table->text('abilities')->nullable();
`->text` why not `->json` ?

2022-06-29 22:58 UTC, acidjazz commented on migrations/create_humble_tables.php
> +            $table->text('abilities')->nullable();
https://laravel.com/docs/9.x/migrations#column-method-json

2022-06-29 22:58 UTC, acidjazz commented
Can you also update the readme with these features/exmples?

2022-06-29 23:06 UTC, tcampbPPU commented on migrations/create_humble_tables.php
> +            $table->text('abilities')->nullable();
sure I think it could be `->json()` I just copied what Sanctum does. But I don't expect the `abilities` to be anything more then a flat array

2022-06-30 03:37 UTC, tcampbPPU commented on config/humble.php
> +    'active_session_time' => 300, // 5 minutes
Lets user define how long active session time is declared as.

2022-06-30 03:37 UTC, tcampbPPU commented on migrations/create_humble_tables.php
> +            $table->json('abilities')->nullable();
abilities column add-on

2022-06-30 03:37 UTC, tcampbPPU commented on src/Traits/Humble.php
> +    public function createToken(string $source, array $abilities = ['*']): string
easy way for user to create new session token record

2022-06-30 15:30 UTC, acidjazz commented on migrations/create_humble_tables.php
> +            $table->text('abilities')->nullable();
I think ->json() is better for MySQL

> Optimized storage format. JSON documents stored in JSON columns are converted to an internal format that permits quick read access to document elements. When the server later must read a JSON value stored in this binary format, the value need not be parsed from a text representation. The binary format is structured to enable the server to look up subobjects or nested values directly by key or array index without reading all values before or after them in the document.

2022-06-30 19:05 UTC, merged